-- MySQL Script generated by MySQL Workbench
-- Sat Jul 29 11:50:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trabalho_Bando_Dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trabalho_Bando_Dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabalho_Bando_Dados` DEFAULT CHARACTER SET utf8mb4 ;
USE `Trabalho_Bando_Dados` ;

-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Clientes` (
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Endereço` VARCHAR(90) NOT NULL,
  `Telefone` INT(13) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Atendente` (
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Salario` DECIMAL NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Ordem de Serviço` (
  `Número` INT(30) NOT NULL,
  `Data` DATE NOT NULL,
  `Total` DECIMAL NOT NULL,
  `Todos os serviços realizados` LONGTEXT NOT NULL,
  `Todas as peças utilizadas` LONGTEXT NOT NULL,
  `Atendente_CPF` INT(11) NOT NULL,
  `Clientes_CPF` INT(11) NOT NULL,
  PRIMARY KEY (`Número`),
  INDEX `fk_Ordem de Serviço_Atendente1_idx` (`Atendente_CPF` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Clientes1_idx` (`Clientes_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Atendente1`
    FOREIGN KEY (`Atendente_CPF`)
    REFERENCES `Trabalho_Bando_Dados`.`Atendente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Clientes1`
    FOREIGN KEY (`Clientes_CPF`)
    REFERENCES `Trabalho_Bando_Dados`.`Clientes` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Peça` (
  `Código da Peça` DECIMAL NOT NULL,
  `Descrição` LONGTEXT NOT NULL,
  `Estoque` REAL NOT NULL,
  `Preço` DECIMAL NOT NULL,
  PRIMARY KEY (`Código da Peça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Serviço a ser realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Serviço a ser realizado` (
  `Código Serviço` INT(50) NOT NULL AUTO_INCREMENT,
  `Descrição` LONGTEXT NOT NULL,
  `Valor` DECIMAL NOT NULL,
  PRIMARY KEY (`Código Serviço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Ordem de Serviço_has_Serviço a ser realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Ordem de Serviço_has_Serviço a ser realizado` (
  `Ordem de Serviço_Número` INT(30) NOT NULL,
  `Serviço a ser realizado_Código Serviço` INT(50) NOT NULL,
  PRIMARY KEY (`Ordem de Serviço_Número`, `Serviço a ser realizado_Código Serviço`),
  INDEX `fk_Ordem de Serviço_has_Serviço a ser realizado_Serviço _idx` (`Serviço a ser realizado_Código Serviço` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Serviço a ser realizado_Ordem de _idx` (`Ordem de Serviço_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço a ser realizado_Ordem de Se1`
    FOREIGN KEY (`Ordem de Serviço_Número`)
    REFERENCES `Trabalho_Bando_Dados`.`Ordem de Serviço` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço a ser realizado_Serviço a 1`
    FOREIGN KEY (`Serviço a ser realizado_Código Serviço`)
    REFERENCES `Trabalho_Bando_Dados`.`Serviço a ser realizado` (`Código Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabalho_Bando_Dados`.`Ordem de Serviço_has_Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabalho_Bando_Dados`.`Ordem de Serviço_has_Peça` (
  `Ordem de Serviço_Número` INT(30) NOT NULL,
  `Peça_Código da Peça` DECIMAL NOT NULL,
  PRIMARY KEY (`Ordem de Serviço_Número`, `Peça_Código da Peça`),
  INDEX `fk_Ordem de Serviço_has_Peça_Peça1_idx` (`Peça_Código da Peça` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Peça_Ordem de Serviço1_idx` (`Ordem de Serviço_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Peça_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_Número`)
    REFERENCES `Trabalho_Bando_Dados`.`Ordem de Serviço` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Peça_Peça1`
    FOREIGN KEY (`Peça_Código da Peça`)
    REFERENCES `Trabalho_Bando_Dados`.`Peça` (`Código da Peça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
